using NativeMethods;

namespace System.Windows.Forms
{
    public abstract partial class FileOpenDialog
    {
        public enum FileOpenDialogOptions : uint
        {
            OverwritePrompt = FILEOPENDIALOGOPTIONS.FOS_OVERWRITEPROMPT,
            StrictFileTypes = FILEOPENDIALOGOPTIONS.FOS_STRICTFILETYPES,
            NochangeDir = FILEOPENDIALOGOPTIONS.FOS_NOCHANGEDIR,
            PickFolders = FILEOPENDIALOGOPTIONS.FOS_PICKFOLDERS,
            ForceFileSystem = FILEOPENDIALOGOPTIONS.FOS_FORCEFILESYSTEM,
            AllNonStorageItems = FILEOPENDIALOGOPTIONS.FOS_ALLNONSTORAGEITEMS,
            NoValidate = FILEOPENDIALOGOPTIONS.FOS_NOVALIDATE,
            AllowMultiSelect = FILEOPENDIALOGOPTIONS.FOS_ALLOWMULTISELECT,
            PathMustExist = FILEOPENDIALOGOPTIONS.FOS_PATHMUSTEXIST,
            FileMustExist = FILEOPENDIALOGOPTIONS.FOS_FILEMUSTEXIST,
            CreatePrompt = FILEOPENDIALOGOPTIONS.FOS_CREATEPROMPT,
            ShareAware = FILEOPENDIALOGOPTIONS.FOS_SHAREAWARE,
            NoReadonlyReturn = FILEOPENDIALOGOPTIONS.FOS_NOREADONLYRETURN,
            NoTestFileCreate = FILEOPENDIALOGOPTIONS.FOS_NOTESTFILECREATE,
            HideMRUPlaces = FILEOPENDIALOGOPTIONS.FOS_HIDEMRUPLACES,
            HidePinnedPlaces = FILEOPENDIALOGOPTIONS.FOS_HIDEPINNEDPLACES,
            NoDereferenceLinks = FILEOPENDIALOGOPTIONS.FOS_NODEREFERENCELINKS,
            OKButtonNeedsInteraction = FILEOPENDIALOGOPTIONS.FOS_OKBUTTONNEEDSINTERACTION,
            DontAddToRecent = FILEOPENDIALOGOPTIONS.FOS_DONTADDTORECENT,
            ForceShowHidden = FILEOPENDIALOGOPTIONS.FOS_FORCESHOWHIDDEN,
            DefaultNoMiniMode = FILEOPENDIALOGOPTIONS.FOS_DEFAULTNOMINIMODE,
            ForcePreviewPaneOn = FILEOPENDIALOGOPTIONS.FOS_FORCEPREVIEWPANEON,
            SupportStreamableItems = FILEOPENDIALOGOPTIONS.FOS_SUPPORTSTREAMABLEITEMS
        }
    }
}
